# Generated by Django 5.1.1 on 2024-09-21 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountName', models.CharField(max_length=100)),
                ('AccountType', models.CharField(max_length=50)),
                ('Created_At', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiscountCode', models.CharField(max_length=50)),
                ('DiscountDesc', models.TextField()),
                ('DiscountType', models.CharField(max_length=50)),
                ('DiscountValue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GatewayName', models.CharField(max_length=100)),
                ('GatewayDetails', models.TextField()),
                ('Created_At', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reservation', models.IntegerField(blank=True, null=True)),
                ('ProductOrder', models.IntegerField(blank=True, null=True)),
                ('Order', models.IntegerField(blank=True, null=True)),
                ('TransactionCode', models.CharField(max_length=100)),
                ('TransactionTypeDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountCode', models.CharField(max_length=100)),
                ('AccountDesc', models.TextField()),
                ('NatureFlag', models.BooleanField()),
                ('Created_At', models.DateField(auto_now_add=True)),
                ('AccountType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentType', models.CharField(max_length=50)),
                ('PaymentDate', models.DateField()),
                ('Gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paymentgateway')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionNo', models.CharField(max_length=100)),
                ('TransactionStatus', models.CharField(max_length=50)),
                ('Particulars', models.TextField()),
                ('Created_By', models.CharField(max_length=100)),
                ('Reviewed_By', models.CharField(max_length=100)),
                ('Date_Reviewed', models.DateField(blank=True, null=True)),
                ('Date_Cancelled', models.DateField(blank=True, null=True)),
                ('TransactionDate', models.DateField()),
                ('Discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.discounts')),
                ('Payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.payments')),
                ('TransactionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DebitAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreditAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chartofaccs')),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='TRTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particulars', models.TextField()),
                ('TransactionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactiontype')),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='TRTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trtemplate'),
        ),
        migrations.CreateModel(
            name='TRTemplateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DC_Flag', models.BooleanField()),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chartofaccs')),
                ('TRTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trtemplate')),
            ],
        ),
    ]
