# Generated by Django 5.0 on 2025-04-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_journalentry_adjusted_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='Adjusted_Entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
