# Generated by Django 5.1.1 on 2025-01-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_transactions_discount_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry_No', models.CharField(max_length=100)),
                ('Entry_Date', models.DateField()),
                ('EntryParticulars', models.TextField()),
                ('DebitAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreditAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Created_By', models.CharField(max_length=100)),
                ('Reviewed_By', models.CharField(blank=True, max_length=100, null=True)),
                ('Review_Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_Reviewed', models.DateField(blank=True, null=True)),
                ('Date_Cancelled', models.DateField(blank=True, null=True)),
                ('EntryStatus_FK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.entrystatus')),
                ('TRTemplate_FK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.trtemplate')),
                ('TransactionType_FK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.transactiontype')),
            ],
        ),
        migrations.DeleteModel(
            name='Discounts',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='Gateway',
        ),
        migrations.RemoveField(
            model_name='transactiondetails',
            name='Account_FK',
        ),
        migrations.RemoveField(
            model_name='transactiondetails',
            name='Transaction_FK',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='TRTemplate_FK',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='TransactionType_FK',
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='TransactionDetails',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
