# Generated by Django 5.1.1 on 2025-01-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entrystatus_journalentry_delete_discounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='CreditAmount',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='DebitAmount',
        ),
        migrations.CreateModel(
            name='JournalEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DebitAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('CreditAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Account_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chartofaccs')),
                ('JournalEntry_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.journalentry')),
            ],
        ),
    ]
