# Generated by Django 5.1.1 on 2025-01-12 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_journalentry_creditamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='Created_By',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='EntryStatus_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.entrystatus'),
        ),
    ]
