# Generated by Django 5.1.1 on 2025-01-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_journalentry_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='EntryStatus_FK',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.entrystatus'),
        ),
    ]
