# Generated by Django 5.1.1 on 2025-01-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_paymentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='PaymentDate',
            field=models.DateField(),
        ),
    ]
