# Generated by Django 5.1.1 on 2025-02-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_paymentrecord_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='transaction_id',
            field=models.CharField(max_length=255),
        ),
    ]
