# Generated by Django 5.1.1 on 2025-02-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_paymentrecord_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
