# Generated by Django 5.1.1 on 2025-02-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_paymentrecord_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='EntryCreated',
            field=models.BooleanField(default=0),
        ),
    ]
