# Generated by Django 5.1.2 on 2024-11-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_accountsetuptoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountSetupToken',
        ),
    ]
