# Generated by Django 5.1.2 on 2024-11-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_create_groups'),
        ('authentication', '0006_delete_accountsetuptoken'),
    ]

    operations = [
    ]
