# Generated by Django 5.1.2 on 2024-11-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_merge_20241113_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=50),
        ),
    ]
