# Generated by Django 5.1.2 on 2024-11-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_employee_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('employee', 'Employee')], default='employee', max_length=50),
        ),
    ]
