# Generated by Django 5.1.2 on 2024-11-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_employee_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='security_question_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='security_question_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='security_question_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
