# Generated by Django 5.1.2 on 2024-10-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
